name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          conda env update -f environment.yml --prune
          conda activate hf-bench-env
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Run tests
        run: pytest tests/